Update mainnet-erc1155.md
abridged/collabland-dev pull request #207
Opened 2023-12-12 12:55 UTC by Crypt0P0rtf0li0

2023-12-15 20:19 UTC, iSpeakNerd commented on help-docs/command-center/create-a-tgr/evm/mainnet-erc1155.md
> +## Prerequisites
make level 3 header
`### `

2023-12-15 20:19 UTC, iSpeakNerd commented on help-docs/command-center/create-a-tgr/evm/mainnet-erc1155.md
> +## Instructions
make level 3 header 
`###`

2023-12-15 20:22 UTC, iSpeakNerd commented on help-docs/command-center/create-a-tgr/evm/mainnet-erc1155.md
> +```js
change to
```
jsx title="ERC1155 TokenIds Script"
```

2023-12-15 20:24 UTC, iSpeakNerd requested changes
check the comments and resolve please @Crypt0P0rtf0li0

2023-12-15 20:24 UTC, iSpeakNerd commented on help-docs/command-center/create-a-tgr/evm/mainnet-erc1155.md
>  ```jsx title="ERC1155 TokenIds Script"
remove this code block

2023-12-15 20:24 UTC, iSpeakNerd commented on help-docs/command-center/create-a-tgr/evm/mainnet-erc1155.md
> +
Add level 2 header
```
## Get All ERC1155 tokenIds Via OpenSea API
```

2023-12-16 12:36 UTC, Crypt0P0rtf0li0 commented
Changes updated.

2023-12-17 01:02 UTC, iSpeakNerd approved these changes
looks good ty

2023-12-17 01:02 UTC, merged